### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by demonlibra** [NSUHackspace/FreeCAD_immersion#1]
**Нерабочая ссылка**
Страница 1
Эскиз и технический рисунок https://www.youtube.com/watch?v=neHha8KLKcc

**Неточность**
Страница 1
в первую очередь мы будем пользоваться только одним Part Design.
в первую очередь мы будем пользоваться только Part Design и Sketcher.

**Comment by lazymanul** [comment]
Спасибо, исправлено
